#!/usr/bin/env sh
# Generates src/grammars_ext/: one compiled native Zig grammar module per
# grammars/textmate/*.tmLanguage.json (excluding the 25 native languages),
# plus a root.zig exposing names + modules + idFromName for the
# `wasm-api-full` experiment build. Output directory is gitignored;
# re-run this script to regenerate.
set -eu

zhlc=${ZHLC:-zig-out/bin/zhlc}
out_dir=src/grammars_ext
log_dir=${ZHL_EXT_LOG_DIR:-/tmp/zhl-grammars-ext-logs}

if [ ! -x "$zhlc" ]; then
    printf 'missing zhlc at %s; run zig build -Doptimize=ReleaseFast first\n' "$zhlc" >&2
    exit 1
fi

rm -rf "$out_dir" "$log_dir"
mkdir -p "$out_dir" "$log_dir"

# Canonical names owned by the native grammar set (native wins).
native_names="bash c cpp csharp css go html java javascript jsx json kotlin markdown php python ruby rust sql swift toml tsx typescript xml yaml zig"

jobs=${ZHL_EXT_JOBS:-16}
find grammars/textmate -maxdepth 1 -type f -name '*.tmLanguage.json' -print0 |
    xargs -0 -r -n 1 -P "$jobs" sh -c '
        zhlc=$1
        out_dir=$2
        log_dir=$3
        native_names=$4
        grammar=$5
        lang=${grammar##*/}
        lang=${lang%.tmLanguage.json}
        for n in $native_names; do
            if [ "$lang" = "$n" ]; then
                echo "$lang" >> "$log_dir/skipped-native"
                exit 0
            fi
        done
        mod=$(printf %s "$lang" | tr -c "a-zA-Z0-9_" "_")
        tmp="$log_dir/$mod.zhl"
        if ! "$zhlc" convert-textmate-json "$grammar" "$tmp" --include-dir grammars/textmate \
                > "$log_dir/$mod.convert.log" 2>&1; then
            echo "$lang" >> "$log_dir/failed-convert"
            exit 0
        fi
        if ! "$zhlc" compile-native "$tmp" "$out_dir/$mod.zig" \
                > "$log_dir/$mod.compile.log" 2>&1; then
            echo "$lang" >> "$log_dir/failed-compile"
            rm -f "$out_dir/$mod.zig"
            exit 0
        fi
        echo "$lang $mod" >> "$log_dir/ok"
    ' sh "$zhlc" "$out_dir" "$log_dir" "$native_names"

touch "$log_dir/ok" "$log_dir/skipped-native" "$log_dir/failed-convert" "$log_dir/failed-compile"
sort -o "$log_dir/ok" "$log_dir/ok"

# Drop grammars known to blow the comptime eval branch quota when the engine
# is instantiated (see tools/grammars_ext_exclude.txt).
exclude_file=tools/grammars_ext_exclude.txt
if [ -f "$exclude_file" ]; then
    awk 'NR==FNR { if ($0 !~ /^#/ && $0 != "") skip[$0] = 1; next } !($2 in skip)' \
        "$exclude_file" "$log_dir/ok" > "$log_dir/ok.included"
    awk 'NR==FNR { if ($0 !~ /^#/ && $0 != "") skip[$0] = 1; next } ($2 in skip)' \
        "$exclude_file" "$log_dir/ok" > "$log_dir/excluded"
    mv "$log_dir/ok.included" "$log_dir/ok"
else
    : > "$log_dir/excluded"
fi

root="$out_dir/root.zig"
{
    echo '//! Generated by tools/generate_grammars_ext.sh. Do not edit.'
    echo 'const std = @import("std");'
    echo ''
    echo '/// Ext language ids start here; id = base_id + index into `names`.'
    echo 'pub const base_id: u32 = 1000;'
    echo ''
    while read -r lang mod; do
        echo "pub const g_$mod = @import(\"$mod.zig\");"
    done < "$log_dir/ok"
    echo ''
    echo 'pub const names = [_][]const u8{'
    while read -r lang mod; do
        echo "    \"$lang\","
    done < "$log_dir/ok"
    echo '};'
    echo ''
    echo 'pub const modules = .{'
    while read -r lang mod; do
        echo "    g_$mod,"
    done < "$log_dir/ok"
    echo '};'
    echo ''
    cat <<'EOF'
/// Returns base_id + index for a known ext grammar name, 0 otherwise.
pub fn idFromName(name: []const u8) u32 {
    for (&names, 0..) |n, i| {
        if (std.mem.eql(u8, name, n)) return base_id + @as(u32, @intCast(i));
    }
    return 0;
}
EOF
} > "$root"

total=$(find grammars/textmate -maxdepth 1 -type f -name '*.tmLanguage.json' | wc -l | tr -d ' ')
ok=$(wc -l < "$log_dir/ok" | tr -d ' ')
skipped=$(wc -l < "$log_dir/skipped-native" | tr -d ' ')
excluded=$(wc -l < "$log_dir/excluded" | tr -d ' ')
fconv=$(wc -l < "$log_dir/failed-convert" | tr -d ' ')
fcomp=$(wc -l < "$log_dir/failed-compile" | tr -d ' ')
printf 'total=%s included=%s skipped-native=%s excluded=%s failed-convert=%s failed-compile=%s\n' \
    "$total" "$ok" "$skipped" "$excluded" "$fconv" "$fcomp"
if [ "$fconv" -gt 0 ]; then
    printf 'failed-convert: %s\n' "$(tr '\n' ' ' < "$log_dir/failed-convert")"
fi
if [ "$fcomp" -gt 0 ]; then
    printf 'failed-compile: %s\n' "$(tr '\n' ' ' < "$log_dir/failed-compile")"
fi
